//! Compiles the help text in `docs/cli-help.json` into the binary.
//!
//! The same file feeds the site's /docs page, so the two can't drift. Here it
//! is laid out for an 80-column terminal and written out as Rust constants
//! (`$OUT_DIR/help_text.rs`, included by `src/help.rs`):
//!
//!   SUMMARY, LONG_ABOUT, AFTER_HELP, AFTER_LONG_HELP   for `agent-graph`
//!   <command>::{SUMMARY, DESCRIPTION, EXAMPLES}        for each command
//!   <command>::opt::<OPTION>                           for each option
//!
//! A malformed file fails the build, and so does an option the CLI uses but
//! the file doesn't describe (the constant won't exist).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde_json::Value;

const SOURCE: &str = "docs/cli-help.json";
const WIDTH: usize = 80;

fn main() {
    println!("cargo:rerun-if-changed={SOURCE}");
    let text = fs::read_to_string(SOURCE).unwrap_or_else(|e| panic!("reading {SOURCE}: {e}"));
    let help: Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("{SOURCE} isn't valid JSON: {e}"));

    let mut out = String::from("// Generated by build.rs from docs/cli-help.json. Don't edit.\n\n");
    let summary = string(&help, "summary");
    constant(&mut out, "SUMMARY", &summary);
    constant(
        &mut out,
        "LONG_ABOUT",
        &format!("{summary}\n\n{}", blocks(array(&help, "description"), 0)),
    );
    let quick: Vec<String> = array(&help, "quickStart")
        .iter()
        .map(|v| as_str(v, "quickStart").to_string())
        .collect();
    constant(&mut out, "AFTER_HELP", &quick.join("\n"));

    let mut long = Vec::new();
    for section in array(&help, "sections") {
        let title = string(section, "title");
        let body = match section.get("examples") {
            Some(examples) => examples_text(examples.as_array().expect("examples is a list")),
            None => blocks(array(section, "blocks"), 2),
        };
        long.push(format!("{title}:\n{body}"));
    }
    long.push(string(&help, "footer"));
    constant(&mut out, "AFTER_LONG_HELP", &long.join("\n\n"));

    for command in array(&help, "commands") {
        let name = string(command, "name");
        writeln!(
            out,
            "\n/// `agent-graph {name}`\npub mod {} {{",
            ident(&name)
        )
        .unwrap();
        constant(&mut out, "SUMMARY", &string(command, "summary"));
        constant(
            &mut out,
            "DESCRIPTION",
            &blocks(array(command, "description"), 0),
        );
        constant(
            &mut out,
            "EXAMPLES",
            &format!("Examples:\n{}", examples_text(array(command, "examples"))),
        );
        out.push_str("pub mod opt {\n");
        for option in array(command, "options") {
            constant(
                &mut out,
                &ident(&string(option, "id")).to_uppercase(),
                &string(option, "text"),
            );
        }
        out.push_str("}\n}\n");
    }

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("help_text.rs");
    fs::write(dest, out).unwrap();
}

fn constant(out: &mut String, name: &str, value: &str) {
    // `{:?}` gives a valid Rust string literal.
    writeln!(out, "pub const {name}: &str = {value:?};").unwrap();
}

fn ident(name: &str) -> String {
    name.replace('-', "_")
}

fn string(value: &Value, key: &str) -> String {
    as_str(
        value
            .get(key)
            .unwrap_or_else(|| panic!("{SOURCE}: missing \"{key}\"")),
        key,
    )
    .to_string()
}

fn as_str<'a>(value: &'a Value, key: &str) -> &'a str {
    value
        .as_str()
        .unwrap_or_else(|| panic!("{SOURCE}: \"{key}\" should be a string"))
}

fn array<'a>(value: &'a Value, key: &str) -> &'a Vec<Value> {
    value
        .get(key)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("{SOURCE}: \"{key}\" should be a list"))
}

/// Lays out description blocks. `indent` is where paragraphs start; lists,
/// tables, steps and code are always indented by two.
fn blocks(blocks: &[Value], indent: usize) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut after_heading = false;
    for block in blocks {
        let text = if let Some(t) = block.get("text") {
            wrap(as_str(t, "text"), indent, indent)
        } else if let Some(h) = block.get("heading") {
            format!("{}{}:", " ".repeat(indent), as_str(h, "heading"))
        } else if let Some(items) = block.get("list").and_then(Value::as_array) {
            items
                .iter()
                .map(|i| wrap(&format!("- {}", as_str(i, "list")), 2, 4))
                .collect::<Vec<_>>()
                .join("\n")
        } else if let Some(steps) = block.get("steps").and_then(Value::as_array) {
            steps
                .iter()
                .enumerate()
                .map(|(n, step)| {
                    let text = string(step, "text");
                    match step.get("command") {
                        Some(c) => format!(
                            "  {}. {}\n{}",
                            n + 1,
                            as_str(c, "command"),
                            wrap(&text, 5, 5)
                        ),
                        None => wrap(&format!("{}. {text}", n + 1), 2, 5),
                    }
                })
                .collect::<Vec<_>>()
                .join("\n")
        } else if let Some(rows) = block.get("table").and_then(Value::as_array) {
            table(rows)
        } else if let Some(code) = block.get("code") {
            as_str(code, "code")
                .lines()
                .map(|l| format!("  {l}"))
                .collect::<Vec<_>>()
                .join("\n")
        } else {
            panic!("{SOURCE}: unknown block {block}");
        };
        // A heading sits right on top of what it introduces.
        if after_heading {
            let last = parts.last_mut().unwrap();
            last.push('\n');
            last.push_str(&text);
        } else {
            parts.push(text);
        }
        after_heading = block.get("heading").is_some();
    }
    parts.join("\n\n")
}

/// Two columns: terms, then text wrapped to line up. A term too wide for the
/// column gets a line of its own.
fn table(rows: &[Value]) -> String {
    let rows: Vec<(String, String)> = rows
        .iter()
        .map(|r| {
            let cells = r
                .as_array()
                .filter(|c| c.len() == 2)
                .unwrap_or_else(|| panic!("{SOURCE}: table rows are [term, text]"));
            (
                as_str(&cells[0], "table").to_string(),
                as_str(&cells[1], "table").to_string(),
            )
        })
        .collect();
    let widest = rows
        .iter()
        .map(|(t, _)| t.chars().count())
        .filter(|&w| w <= 32)
        .max()
        .unwrap_or(10);
    let column = 2 + widest + 3;
    rows.iter()
        .map(|(term, text)| {
            let term_width = term.chars().count();
            if term_width > widest {
                format!("  {term}\n{}", wrap(text, column, column))
            } else {
                let body = wrap(text, column, column);
                format!(
                    "  {term}{}{}",
                    " ".repeat(column - 2 - term_width),
                    &body[column..]
                )
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn examples_text(examples: &[Value]) -> String {
    examples
        .iter()
        .map(|e| {
            format!(
                "  {}\n{}",
                string(e, "command"),
                wrap(&string(e, "text"), 6, 6)
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// Word-wraps `text` to WIDTH columns: the first line starts at `first`
/// spaces in, the rest at `rest`. A `code span` is never split.
fn wrap(text: &str, first: usize, rest: usize) -> String {
    let mut words: Vec<String> = Vec::new();
    let mut in_code = false;
    for word in text.split_whitespace() {
        match words.last_mut() {
            Some(last) if in_code => {
                last.push(' ');
                last.push_str(word);
            }
            _ => words.push(word.to_string()),
        }
        if word.matches('`').count() % 2 == 1 {
            in_code = !in_code;
        }
    }
    let mut lines = Vec::new();
    let mut line = " ".repeat(first);
    let mut empty = true;
    for word in &words {
        let fits = line.chars().count() + 1 + word.chars().count() <= WIDTH;
        if !empty && !fits {
            lines.push(std::mem::replace(&mut line, " ".repeat(rest)));
            empty = true;
        }
        if !empty {
            line.push(' ');
        }
        line.push_str(word);
        empty = false;
    }
    lines.push(line);
    lines.join("\n")
}
