//! Compiles the help text in `docs/cli-help.json` into the binary.
//!
//! The same file feeds the site's /docs page, so the two can't drift. Here it
//! is laid out for an 80-column terminal and written out as Rust constants
//! (`$OUT_DIR/help_text.rs`, included by `src/help.rs`):
//!
//!   SUMMARY, LONG_ABOUT, AFTER_HELP, AFTER_LONG_HELP   for `agent-graph`
//!   <command>::{SUMMARY, DESCRIPTION, EXAMPLES}        for each command
//!   <command>::opt::<OPTION>                           for each option
//!
//! A malformed file fails the build, and so does an option the CLI uses but
//! the file doesn't describe (the constant won't exist).
//!
//! For Windows, it also gives agent-graph.exe its icon (`windows_icon`).

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde_json::Value;

const SOURCE: &str = "docs/cli-help.json";
const WIDTH: usize = 80;

fn main() {
    windows_icon();
    println!("cargo:rerun-if-changed={SOURCE}");
    let text = fs::read_to_string(SOURCE).unwrap_or_else(|e| panic!("reading {SOURCE}: {e}"));
    let help: Value =
        serde_json::from_str(&text).unwrap_or_else(|e| panic!("{SOURCE} isn't valid JSON: {e}"));

    let mut out = String::from("// Generated by build.rs from docs/cli-help.json. Don't edit.\n\n");
    let summary = string(&help, "summary");
    constant(&mut out, "SUMMARY", &summary);
    constant(
        &mut out,
        "LONG_ABOUT",
        &format!("{summary}\n\n{}", blocks(array(&help, "description"), 0)),
    );
    let quick: Vec<String> = array(&help, "quickStart")
        .iter()
        .map(|v| as_str(v, "quickStart").to_string())
        .collect();
    constant(&mut out, "AFTER_HELP", &quick.join("\n"));

    let mut long = Vec::new();
    for section in array(&help, "sections") {
        let title = string(section, "title");
        let body = match section.get("examples") {
            Some(examples) => examples_text(examples.as_array().expect("examples is a list")),
            None => blocks(array(section, "blocks"), 2),
        };
        long.push(format!("{title}:\n{body}"));
    }
    long.push(string(&help, "footer"));
    constant(&mut out, "AFTER_LONG_HELP", &long.join("\n\n"));

    for command in array(&help, "commands") {
        let name = string(command, "name");
        writeln!(
            out,
            "\n/// `agent-graph {name}`\npub mod {} {{",
            ident(&name)
        )
        .unwrap();
        constant(&mut out, "SUMMARY", &string(command, "summary"));
        constant(
            &mut out,
            "DESCRIPTION",
            &blocks(array(command, "description"), 0),
        );
        constant(
            &mut out,
            "EXAMPLES",
            &format!("Examples:\n{}", examples_text(array(command, "examples"))),
        );
        out.push_str("pub mod opt {\n");
        for option in array(command, "options") {
            constant(
                &mut out,
                &ident(&string(option, "id")).to_uppercase(),
                &string(option, "text"),
            );
        }
        out.push_str("}\n}\n");
    }

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("help_text.rs");
    fs::write(dest, out).unwrap();
}

/// The icon Explorer and the taskbar show for agent-graph.exe (made by
/// scripts/make-icons.py).
const ICON: &str = "assets/windows/agent-graph.ico";

/// Gives agent-graph.exe its icon, built for Windows: the icon, as a
/// compiled resource file (`.res`), which the linker takes as it is (MSVC's
/// link.exe, or lld-link cross-compiling), so no resource compiler is
/// needed.
fn windows_icon() {
    println!("cargo:rerun-if-changed={ICON}");
    let target = |key: &str| env::var(key).unwrap_or_default();
    if target("CARGO_CFG_TARGET_OS") != "windows" || target("CARGO_CFG_TARGET_ENV") != "msvc" {
        return;
    }
    let ico = fs::read(ICON).unwrap_or_else(|e| panic!("reading {ICON}: {e}"));
    let res = Path::new(&env::var("OUT_DIR").unwrap()).join("agent-graph.res");
    fs::write(&res, icon_resources(&ico)).unwrap();
    println!("cargo:rustc-link-arg-bins={}", res.display());
}

/// An `.ico` file's images as a resource file: each an `RT_ICON`, and a
/// `RT_GROUP_ICON` listing them, which Windows shows as the program's icon
/// (the first group is the one). The layout's Microsoft's: "Resource File
/// Formats" and "ICONDIR".
fn icon_resources(ico: &[u8]) -> Vec<u8> {
    const RT_ICON: u16 = 3;
    const RT_GROUP_ICON: u16 = 14;
    let u16_at = |at: usize| u16::from_le_bytes([ico[at], ico[at + 1]]);
    let u32_at = |at: usize| u32::from_le_bytes(ico[at..at + 4].try_into().unwrap());
    assert!(
        ico.len() >= 6 && u16_at(0) == 0 && u16_at(2) == 1,
        "{ICON} isn't an icon file"
    );
    let count = u16_at(4);

    let mut res = Vec::new();
    // A resource file starts with an empty entry, which says what it is.
    resource(&mut res, 0, 0, 0, &[]);
    // The group: ICONDIR's header, then an entry per image, naming its
    // resource by id rather than giving its place in the file.
    let mut group = ico[..6].to_vec();
    for i in 0..count {
        let entry = 6 + usize::from(i) * 16;
        let (size, offset) = (u32_at(entry + 8) as usize, u32_at(entry + 12) as usize);
        let image = ico
            .get(offset..offset + size)
            .unwrap_or_else(|| panic!("{ICON}: image {i} is cut short"));
        resource(&mut res, RT_ICON, i + 1, 0x1010, image);
        group.extend_from_slice(&ico[entry..entry + 12]);
        group.extend_from_slice(&(i + 1).to_le_bytes());
    }
    resource(&mut res, RT_GROUP_ICON, 1, 0x1030, &group);
    res
}

/// One resource: its header (type and name by number, US English), and its
/// data, padded to four bytes.
fn resource(res: &mut Vec<u8>, kind: u16, name: u16, flags: u16, data: &[u8]) {
    let language: u16 = if kind == 0 { 0 } else { 0x0409 };
    res.extend_from_slice(&(data.len() as u32).to_le_bytes());
    res.extend_from_slice(&32u32.to_le_bytes()); // this header's size
    res.extend_from_slice(&[0xFF, 0xFF]);
    res.extend_from_slice(&kind.to_le_bytes());
    res.extend_from_slice(&[0xFF, 0xFF]);
    res.extend_from_slice(&name.to_le_bytes());
    res.extend_from_slice(&0u32.to_le_bytes()); // data version
    res.extend_from_slice(&flags.to_le_bytes()); // moveable, pure, discardable
    res.extend_from_slice(&language.to_le_bytes());
    res.extend_from_slice(&0u32.to_le_bytes()); // version
    res.extend_from_slice(&0u32.to_le_bytes()); // characteristics
    res.extend_from_slice(data);
    res.resize(res.len().next_multiple_of(4), 0);
}

fn constant(out: &mut String, name: &str, value: &str) {
    // `{:?}` gives a valid Rust string literal.
    writeln!(out, "pub const {name}: &str = {value:?};").unwrap();
}

fn ident(name: &str) -> String {
    name.replace('-', "_")
}

fn string(value: &Value, key: &str) -> String {
    as_str(
        value
            .get(key)
            .unwrap_or_else(|| panic!("{SOURCE}: missing \"{key}\"")),
        key,
    )
    .to_string()
}

fn as_str<'a>(value: &'a Value, key: &str) -> &'a str {
    value
        .as_str()
        .unwrap_or_else(|| panic!("{SOURCE}: \"{key}\" should be a string"))
}

fn array<'a>(value: &'a Value, key: &str) -> &'a Vec<Value> {
    value
        .get(key)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("{SOURCE}: \"{key}\" should be a list"))
}

/// Lays out description blocks. `indent` is where paragraphs start; lists,
/// tables, steps and code are always indented by two.
fn blocks(blocks: &[Value], indent: usize) -> String {
    let mut parts: Vec<String> = Vec::new();
    let mut after_heading = false;
    for block in blocks {
        let text = if let Some(t) = block.get("text") {
            wrap(as_str(t, "text"), indent, indent)
        } else if let Some(h) = block.get("heading") {
            format!("{}{}:", " ".repeat(indent), as_str(h, "heading"))
        } else if let Some(items) = block.get("list").and_then(Value::as_array) {
            items
                .iter()
                .map(|i| wrap(&format!("- {}", as_str(i, "list")), 2, 4))
                .collect::<Vec<_>>()
                .join("\n")
        } else if let Some(steps) = block.get("steps").and_then(Value::as_array) {
            steps
                .iter()
                .enumerate()
                .map(|(n, step)| {
                    let text = string(step, "text");
                    match step.get("command") {
                        Some(c) => format!(
                            "  {}. {}\n{}",
                            n + 1,
                            as_str(c, "command"),
                            wrap(&text, 5, 5)
                        ),
                        None => wrap(&format!("{}. {text}", n + 1), 2, 5),
                    }
                })
                .collect::<Vec<_>>()
                .join("\n")
        } else if let Some(rows) = block.get("table").and_then(Value::as_array) {
            table(rows)
        } else if let Some(code) = block.get("code") {
            as_str(code, "code")
                .lines()
                .map(|l| format!("  {l}"))
                .collect::<Vec<_>>()
                .join("\n")
        } else {
            panic!("{SOURCE}: unknown block {block}");
        };
        // A heading sits right on top of what it introduces.
        if after_heading {
            let last = parts.last_mut().unwrap();
            last.push('\n');
            last.push_str(&text);
        } else {
            parts.push(text);
        }
        after_heading = block.get("heading").is_some();
    }
    parts.join("\n\n")
}

/// Two columns: terms, then text wrapped to line up. A term too wide for the
/// column gets a line of its own.
fn table(rows: &[Value]) -> String {
    let rows: Vec<(String, String)> = rows
        .iter()
        .map(|r| {
            let cells = r
                .as_array()
                .filter(|c| c.len() == 2)
                .unwrap_or_else(|| panic!("{SOURCE}: table rows are [term, text]"));
            (
                as_str(&cells[0], "table").to_string(),
                as_str(&cells[1], "table").to_string(),
            )
        })
        .collect();
    let widest = rows
        .iter()
        .map(|(t, _)| t.chars().count())
        .filter(|&w| w <= 32)
        .max()
        .unwrap_or(10);
    let column = 2 + widest + 3;
    rows.iter()
        .map(|(term, text)| {
            let term_width = term.chars().count();
            if term_width > widest {
                format!("  {term}\n{}", wrap(text, column, column))
            } else {
                let body = wrap(text, column, column);
                format!(
                    "  {term}{}{}",
                    " ".repeat(column - 2 - term_width),
                    &body[column..]
                )
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn examples_text(examples: &[Value]) -> String {
    examples
        .iter()
        .map(|e| {
            format!(
                "  {}\n{}",
                string(e, "command"),
                wrap(&string(e, "text"), 6, 6)
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// Word-wraps `text` to WIDTH columns: the first line starts at `first`
/// spaces in, the rest at `rest`. A `code span` is never split.
fn wrap(text: &str, first: usize, rest: usize) -> String {
    let mut words: Vec<String> = Vec::new();
    let mut in_code = false;
    for word in text.split_whitespace() {
        match words.last_mut() {
            Some(last) if in_code => {
                last.push(' ');
                last.push_str(word);
            }
            _ => words.push(word.to_string()),
        }
        if word.matches('`').count() % 2 == 1 {
            in_code = !in_code;
        }
    }
    let mut lines = Vec::new();
    let mut line = " ".repeat(first);
    let mut empty = true;
    for word in &words {
        let fits = line.chars().count() + 1 + word.chars().count() <= WIDTH;
        if !empty && !fits {
            lines.push(std::mem::replace(&mut line, " ".repeat(rest)));
            empty = true;
        }
        if !empty {
            line.push(' ');
        }
        line.push_str(word);
        empty = false;
    }
    lines.push(line);
    lines.join("\n")
}
